---
title: "MechaCarChallenge"
output: html_notebook
---
```{r}
library(jsonlite)
library(tidyverse)
library(dplyr)
```

```{r}
MechaCar <- read.csv("MechaCar_mpg.csv")
```

```{r}
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = MechaCar)

```

```{r}
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = MechaCar))
```
```{r}
summary_data <- read.csv("Suspension_Coil.csv")
```
```{r}
total_summary <- summary_data %>%  summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(x=PSI),SD=sd(PSI))
```

```{r}
summary_data %>%  summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(x=PSI),SD=sd(PSI))
```

```{r}
lot_summary <- summary_data %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(x=PSI),SD=sd(PSI), .groups = 'keep')
lot_summary
```
```{r}
t.test(summary_data$PSI)
```

```{r}
t.test(lot_summary$Mean, mu=mean(summary_data$PSI))
```

```{r}
t.test(Lot1_summary$PSI, mu=1500)

t.test(Lot2_summary$PSI, mu=1500)

t.test(Lot3_summary$PSI, mu=1500)
```

